In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from plotly.offline import init_notebook_mode, iplot
import cufflinks as cf
cf.go_offline()
import plotly.io as pio
pio.renderers.default = 'vscode'
%matplotlib inline


## Stemming, Lemmatization and Stop Words on corpus

In [4]:
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords


Avul Pakir Jainulabdeen Abdul Kalam was born on 15 October 1931, to a Tamil Muslim family in the pilgrimage centre of Rameswaram on Pamban Island, then in the Madras Presidency and now in the State of Tamil Nadu. His father Jainulabdeen Marakayar was a boat owner and imam of a local mosque;[9] his mother Ashiamma was a housewife.[10][11][12][13] His father owned a ferry that took Hindu pilgrims back and forth between Rameswaram and the now uninhabited Dhanushkodi.[14][15] Kalam was the youngest of four brothers and one sister in his family.[16][17][18] His ancestors had been wealthy Marakayar traders and landowners, with numerous properties and large tracts of land. Marakayar are a Muslim ethnic group found in coastal Tamil Nadu and Sri Lanka who claim descent from Arab traders and local women. The family business had involved trading groceries between the mainland and the island and to and from Sri Lanka, as well as ferrying pilgrims between the mainland and Pamban. With the opening of the Pamban Bridge to the mainland in 1914, however, the businesses failed and the family fortune and properties were lost by the 1920s, apart from the ancestral home. The family was poverty-stricken by the time Kalam was born. As a young boy he had to sell newspapers to add to the family's meager income. [19][20][21]

In his school years, Kalam had average grades but was described as a bright and hardworking student who had a strong desire to learn. He spent hours on his studies, especially Mathematics.[21] After completing his education at the Schwartz Higher Secondary School, Ramanathapuram, Kalam went on to attend Saint Joseph's College, Tiruchirappalli, then affiliated with the University of Madras, from where he graduated in physics in 1954.[22] He moved to Madras in 1955 to study aerospace engineering in Madras Institute of Technology.[13] While Kalam was working on a senior class project, the Dean was dissatisfied with his lack of progress and threatened to revoke his scholarship unless the project was finished within the next three days. Kalam met the deadline, impressing the Dean, who later said to him, "I was putting you under stress and asking you to meet a difficult deadline."[23] He narrowly missed achieving his dream of becoming a fighter pilot, as he placed ninth in qualifiers, and only eight positions were available in the IAF

In [3]:
paragraph = """ Avul Pakir Jainulabdeen Abdul Kalam was born on 15 October 1931, to a Tamil Muslim family in the pilgrimage centre of Rameswaram on Pamban Island, then in the Madras Presidency and now in the State of Tamil Nadu. His father Jainulabdeen Marakayar was a boat owner and imam of a local mosque;[9] his mother Ashiamma was a housewife.[10][11][12][13] His father owned a ferry that took Hindu pilgrims back and forth between Rameswaram and the now uninhabited Dhanushkodi.[14][15] Kalam was the youngest of four brothers and one sister in his family.[16][17][18] His ancestors had been wealthy Marakayar traders and landowners, with numerous properties and large tracts of land. Marakayar are a Muslim ethnic group found in coastal Tamil Nadu and Sri Lanka who claim descent from Arab traders and local women. The family business had involved trading groceries between the mainland and the island and to and from Sri Lanka, as well as ferrying pilgrims between the mainland and Pamban. With the opening of the Pamban Bridge to the mainland in 1914, however, the businesses failed and the family fortune and properties were lost by the 1920s, apart from the ancestral home. The family was poverty-stricken by the time Kalam was born. As a young boy he had to sell newspapers to add to the family's meager income. [19][20][21]

In his school years, Kalam had average grades but was described as a bright and hardworking student who had a strong desire to learn. He spent hours on his studies, especially Mathematics.[21] After completing his education at the Schwartz Higher Secondary School, Ramanathapuram, Kalam went on to attend Saint Joseph's College, Tiruchirappalli, then affiliated with the University of Madras, from where he graduated in physics in 1954.[22] He moved to Madras in 1955 to study aerospace engineering in Madras Institute of Technology.[13] While Kalam was working on a senior class project, the Dean was dissatisfied with his lack of progress and threatened to revoke his scholarship unless the project was finished within the next three days. Kalam met the deadline, impressing the Dean, who later said to him, "I was putting you under stress and asking you to meet a difficult deadline."[23] He narrowly missed achieving his dream of becoming a fighter pilot, as he placed ninth in qualifiers, and only eight positions were available in the IAF"""

In [4]:
paragraph

' Avul Pakir Jainulabdeen Abdul Kalam was born on 15 October 1931, to a Tamil Muslim family in the pilgrimage centre of Rameswaram on Pamban Island, then in the Madras Presidency and now in the State of Tamil Nadu. His father Jainulabdeen Marakayar was a boat owner and imam of a local mosque;[9] his mother Ashiamma was a housewife.[10][11][12][13] His father owned a ferry that took Hindu pilgrims back and forth between Rameswaram and the now uninhabited Dhanushkodi.[14][15] Kalam was the youngest of four brothers and one sister in his family.[16][17][18] His ancestors had been wealthy Marakayar traders and landowners, with numerous properties and large tracts of land. Marakayar are a Muslim ethnic group found in coastal Tamil Nadu and Sri Lanka who claim descent from Arab traders and local women. The family business had involved trading groceries between the mainland and the island and to and from Sri Lanka, as well as ferrying pilgrims between the mainland and Pamban. With the opening

## tokenization  converting paragraph into sentences and words

In [5]:
nltk.download('punkt')
sentences = nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Abhilash\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [6]:
sentences

[' Avul Pakir Jainulabdeen Abdul Kalam was born on 15 October 1931, to a Tamil Muslim family in the pilgrimage centre of Rameswaram on Pamban Island, then in the Madras Presidency and now in the State of Tamil Nadu.',
 'His father Jainulabdeen Marakayar was a boat owner and imam of a local mosque;[9] his mother Ashiamma was a housewife.',
 '[10][11][12][13] His father owned a ferry that took Hindu pilgrims back and forth between Rameswaram and the now uninhabited Dhanushkodi.',
 '[14][15] Kalam was the youngest of four brothers and one sister in his family.',
 '[16][17][18] His ancestors had been wealthy Marakayar traders and landowners, with numerous properties and large tracts of land.',
 'Marakayar are a Muslim ethnic group found in coastal Tamil Nadu and Sri Lanka who claim descent from Arab traders and local women.',
 'The family business had involved trading groceries between the mainland and the island and to and from Sri Lanka, as well as ferrying pilgrims between the mainland 

In [7]:
stemmer = PorterStemmer()

In [8]:
stemmer.stem('goes')

'goe'

In [9]:
lemmatizer = WordNetLemmatizer()

In [10]:
lemmatizer.lemmatize('goes')

'go'

## Cleaning sentences with regular expressions


In [11]:
len(sentences)

17

In [12]:
import re
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    corpus.append(review)



In [13]:
corpus

[' avul pakir jainulabdeen abdul kalam was born on    october       to a tamil muslim family in the pilgrimage centre of rameswaram on pamban island  then in the madras presidency and now in the state of tamil nadu ',
 'his father jainulabdeen marakayar was a boat owner and imam of a local mosque     his mother ashiamma was a housewife ',
 '                 his father owned a ferry that took hindu pilgrims back and forth between rameswaram and the now uninhabited dhanushkodi ',
 '         kalam was the youngest of four brothers and one sister in his family ',
 '             his ancestors had been wealthy marakayar traders and landowners  with numerous properties and large tracts of land ',
 'marakayar are a muslim ethnic group found in coastal tamil nadu and sri lanka who claim descent from arab traders and local women ',
 'the family business had involved trading groceries between the mainland and the island and to and from sri lanka  as well as ferrying pilgrims between the mainland 

In [14]:
len(corpus)

17

### Stemming

In [15]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [16]:
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))
        


avul
pakir
jainulabdeen
abdul
kalam
born
octob
tamil
muslim
famili
pilgrimag
centr
rameswaram
pamban
island
madra
presid
state
tamil
nadu
father
jainulabdeen
marakayar
boat
owner
imam
local
mosqu
mother
ashiamma
housewif
father
own
ferri
took
hindu
pilgrim
back
forth
rameswaram
uninhabit
dhanushkodi
kalam
youngest
four
brother
one
sister
famili
ancestor
wealthi
marakayar
trader
landown
numer
properti
larg
tract
land
marakayar
muslim
ethnic
group
found
coastal
tamil
nadu
sri
lanka
claim
descent
arab
trader
local
women
famili
busi
involv
trade
groceri
mainland
island
sri
lanka
well
ferri
pilgrim
mainland
pamban
open
pamban
bridg
mainland
howev
busi
fail
famili
fortun
properti
lost
apart
ancestr
home
famili
poverti
stricken
time
kalam
born
young
boy
sell
newspap
add
famili
meager
incom
school
year
kalam
averag
grade
describ
bright
hardwork
student
strong
desir
learn
spent
hour
studi
especi
mathemat
complet
educ
schwartz
higher
secondari
school
ramanathapuram
kalam
went
attend
saint
joseph

### lematize

In [17]:
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

avul
pakir
jainulabdeen
abdul
kalam
born
october
tamil
muslim
family
pilgrimage
centre
rameswaram
pamban
island
madras
presidency
state
tamil
nadu
father
jainulabdeen
marakayar
boat
owner
imam
local
mosque
mother
ashiamma
housewife
father
owned
ferry
took
hindu
pilgrim
back
forth
rameswaram
uninhabited
dhanushkodi
kalam
youngest
four
brother
one
sister
family
ancestor
wealthy
marakayar
trader
landowner
numerous
property
large
tract
land
marakayar
muslim
ethnic
group
found
coastal
tamil
nadu
sri
lanka
claim
descent
arab
trader
local
woman
family
business
involved
trading
grocery
mainland
island
sri
lanka
well
ferrying
pilgrim
mainland
pamban
opening
pamban
bridge
mainland
however
business
failed
family
fortune
property
lost
apart
ancestral
home
family
poverty
stricken
time
kalam
born
young
boy
sell
newspaper
add
family
meager
income
school
year
kalam
average
grade
described
bright
hardworking
student
strong
desire
learn
spent
hour
study
especially
mathematics
completing
education
schwar

## Bag of words

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv = CountVectorizer()

In [20]:
X = cv.fit_transform(corpus)

In [21]:
cv.vocabulary_

{'avul': 19,
 'pakir': 129,
 'jainulabdeen': 90,
 'abdul': 0,
 'kalam': 92,
 'was': 183,
 'born': 25,
 'on': 123,
 'october': 121,
 'to': 174,
 'tamil': 165,
 'muslim': 113,
 'family': 56,
 'in': 85,
 'the': 168,
 'pilgrimage': 132,
 'centre': 34,
 'of': 122,
 'rameswaram': 145,
 'pamban': 130,
 'island': 89,
 'then': 169,
 'madras': 102,
 'presidency': 138,
 'and': 8,
 'now': 119,
 'state': 158,
 'nadu': 114,
 'his': 77,
 'father': 57,
 'marakayar': 104,
 'boat': 24,
 'owner': 128,
 'imam': 83,
 'local': 100,
 'mosque': 110,
 'mother': 111,
 'ashiamma': 13,
 'housewife': 80,
 'owned': 127,
 'ferry': 58,
 'that': 167,
 'took': 175,
 'hindu': 76,
 'pilgrims': 133,
 'back': 20,
 'forth': 62,
 'between': 23,
 'uninhabited': 180,
 'dhanushkodi': 46,
 'youngest': 198,
 'four': 65,
 'brothers': 29,
 'one': 124,
 'sister': 155,
 'ancestors': 6,
 'had': 71,
 'been': 22,
 'wealthy': 184,
 'traders': 177,
 'landowners': 95,
 'with': 191,
 'numerous': 120,
 'properties': 141,
 'large': 97,
 'trac

In [22]:
X[0].toarray()

array([[1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 3, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]], dtype=int64)

In [23]:
corpus[0]

' avul pakir jainulabdeen abdul kalam was born on    october       to a tamil muslim family in the pilgrimage centre of rameswaram on pamban island  then in the madras presidency and now in the state of tamil nadu '

### Apply lemmatize and Stopwords

In [24]:
import re
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    reviews = review.split()
    reviews = [lemmatizer.lemmatize(word) for word in reviews if not word in set(stopwords.words('english'))]
    review = ' '.join(reviews)
    corpus.append(review)

In [25]:
corpus

['avul pakir jainulabdeen abdul kalam born october tamil muslim family pilgrimage centre rameswaram pamban island madras presidency state tamil nadu',
 'father jainulabdeen marakayar boat owner imam local mosque mother ashiamma housewife',
 'father owned ferry took hindu pilgrim back forth rameswaram uninhabited dhanushkodi',
 'kalam youngest four brother one sister family',
 'ancestor wealthy marakayar trader landowner numerous property large tract land',
 'marakayar muslim ethnic group found coastal tamil nadu sri lanka claim descent arab trader local woman',
 'family business involved trading grocery mainland island sri lanka well ferrying pilgrim mainland pamban',
 'opening pamban bridge mainland however business failed family fortune property lost apart ancestral home',
 'family poverty stricken time kalam born',
 'young boy sell newspaper add family meager income',
 'school year kalam average grade described bright hardworking student strong desire learn',
 'spent hour study espe

In [26]:
cv = CountVectorizer(binary=True, ngram_range=(2, 3))

In [27]:
X = cv.fit_transform(corpus)

In [28]:
cv.vocabulary_

{'avul pakir': 25,
 'pakir jainulabdeen': 237,
 'jainulabdeen abdul': 144,
 'abdul kalam': 0,
 'kalam born': 152,
 'born october': 33,
 'october tamil': 227,
 'tamil muslim': 319,
 'muslim family': 213,
 'family pilgrimage': 92,
 'pilgrimage centre': 247,
 'centre rameswaram': 47,
 'rameswaram pamban': 275,
 'pamban island': 241,
 'island madras': 140,
 'madras presidency': 183,
 'presidency state': 257,
 'state tamil': 305,
 'tamil nadu': 321,
 'avul pakir jainulabdeen': 26,
 'pakir jainulabdeen abdul': 238,
 'jainulabdeen abdul kalam': 145,
 'abdul kalam born': 1,
 'kalam born october': 153,
 'born october tamil': 34,
 'october tamil muslim': 228,
 'tamil muslim family': 320,
 'muslim family pilgrimage': 214,
 'family pilgrimage centre': 93,
 'pilgrimage centre rameswaram': 248,
 'centre rameswaram pamban': 48,
 'rameswaram pamban island': 276,
 'pamban island madras': 242,
 'island madras presidency': 141,
 'madras presidency state': 184,
 'presidency state tamil': 258,
 'state tami

In [29]:
corpus[0]

'avul pakir jainulabdeen abdul kalam born october tamil muslim family pilgrimage centre rameswaram pamban island madras presidency state tamil nadu'

In [30]:
X[0].toarray()

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [31]:
X[0].shape 

(1, 360)

## TF-IDF

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(ngram_range=(1,1), max_features=10)
X = cv.fit_transform(corpus)

In [33]:
corpus[0]

'avul pakir jainulabdeen abdul kalam born october tamil muslim family pilgrimage centre rameswaram pamban island madras presidency state tamil nadu'

In [34]:
X[0].toarray()

array([[0.        , 0.27287662, 0.25413745, 0.35141047, 0.        ,
        0.        , 0.35141047, 0.        , 0.        , 0.78356485]])

## Task

In [35]:
import chardet

with open('./data/Complete_data.txt', 'rb') as f:
    data = f.read()
    result = chardet.detect(data)
    data = data.decode(result['encoding'])
    sentences = nltk.sent_tokenize(data)

In [36]:
sentences

['0.1\r\n§ 1.The Buddha: "What do you think, Rahula: What is a mirror for?',
 '"The Buddha:Rahula: "For reflection, sir.',
 '"Rahula:The Buddha: "In the same way, Rahula, bodily acts, verbal acts, & mental acts are to be done with repeated reflection.The Buddha:"Whenever you want to perform a bodily act, you should reflect on it: \'This bodily act I want to perform — would it lead to self-affliction, to the affliction of others, or to both?',
 "Is it an unskillful bodily act, with painful consequences, painful results?'",
 'If, on reflection, you know that it would lead to self-affliction, to the affliction of others, or to both; it would be an unskillful bodily act with painful consequences, painful results, then any bodily act of that sort is absolutely unfit for you to do.',
 'But if on reflection you know that it would not cause affliction... it would be a skillful bodily act with happy consequences, happy results, then any bodily act of that sort is fit for you to do.',
 '(Similar

In [37]:
len(sentences)

9418

In [38]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()





corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [39]:
corpus

['buddha think rahula mirror',
 'buddha rahula reflection sir',
 'rahula buddha way rahula bodily act verbal act mental act done repeated reflection buddha whenever want perform bodily act reflect bodily act want perform would lead self affliction affliction others',
 'unskillful bodily act painful consequence painful result',
 'reflection know would lead self affliction affliction others would unskillful bodily act painful consequence painful result bodily act sort absolutely unfit',
 'reflection know would cause affliction would skillful bodily act happy consequence happy result bodily act sort fit',
 'similarly verbal act mental act',
 'performing bodily act reflect bodily act leading self affliction affliction others',
 'unskillful bodily act painful consequence painful result',
 'reflection know leading self affliction affliction others give',
 'reflection know may continue',
 'similarly verbal act mental act',
 'performed bodily act reflect',
 'reflection know led self affliction

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(ngram_range=(3, 3), max_features=10)

In [41]:
X = cv.fit_transform(corpus)

In [42]:
X[0]

<1x10 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [43]:
X[0].toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Word2Vec

In [5]:
import gensim

In [6]:
 from gensim.models import Word2Vec, KeyedVectors

## Using  a pretrained model

In [47]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [48]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [49]:
wv['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [50]:
wv.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

## Cosine distance/Similarity

In [51]:
wv.similarity('man', 'king')

0.22942673

In [55]:
wv.similarity('gender', 'male')

0.46119848

In [57]:
vec = wv['king']-wv['man']+wv['woman']

In [58]:
wv.most_similar(vec)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

## Spam or Ham

In [7]:
messages = pd.read_csv('../data/SMSSpamCollection.csv', sep='\t', names=["label", "message"])

In [8]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
messages.shape

(5572, 2)

In [11]:
messages.message.loc[100]

"Please don't text me anymore. I have nothing else to say."

In [12]:
## Data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Abhilash\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [16]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z0-9]', ' ', messages['message'][i]) # Remove all characters except a-z and A-Z
    review = review.lower() # Convert all characters to lowercase
    review = review.split() # Split the string into a list
    ps = PorterStemmer() # Create an object of the PorterStemmer class
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')] # Remove all stopwords and apply stemming
    review = ' '.join(review) # Join the list into a string
    corpus.append(review) # Append the string to the corpus list



In [17]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

## Bag of words model

In [18]:
# creating bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, binary=True)
X = cv.fit_transform(corpus).toarray()

In [19]:
y = pd.get_dummies(messages['label'])
y = y.iloc[:,1].values

In [20]:
y

array([False, False,  True, ..., False, False, False])

In [21]:
# Train test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [24]:
#prediction
y_pred = spam_detect_model.predict(X_test)

In [25]:
y_pred

array([False, False, False, ..., False, False, False])

In [27]:
from sklearn import metrics
score = metrics.accuracy_score(y_test, y_pred)
score

0.9838565022421525

In [30]:
report=metrics.classification_report(y_test, y_pred, digits=3)

In [32]:
print(report)

              precision    recall  f1-score   support

       False      0.991     0.991     0.991       966
        True      0.940     0.940     0.940       149

    accuracy                          0.984      1115
   macro avg      0.965     0.965     0.965      1115
weighted avg      0.984     0.984     0.984      1115



## TFIDF model

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500)
X = tv.fit_transform(corpus).toarray()

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [37]:
y_pred = spam_detect_model.predict(X_test)

In [39]:
score = metrics.accuracy_score(y_test, y_pred)
score

0.9838565022421525

In [41]:
report=metrics.classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

       False       0.98      1.00      0.99       966
        True       0.99      0.89      0.94       149

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



## Word2vec Implementation

In [44]:
wv

In [73]:
from nltk.stem import WordNetLemmatizer
ls = WordNetLemmatizer()

In [76]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i]) # Remove all characters except a-z and A-Z
    review = review.lower() # Convert all characters to lowercase
    review = review.split() # Split the string into a list
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review) # Join the list into a string
    corpus.append(review) # Append the string to the corpus list

In [77]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [78]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [79]:
corpus[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [80]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [81]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

In [82]:
## training Word2Vec from Scratch
import gensim
model = gensim.models.Word2Vec(words, window=5, min_count=2) 

In [83]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'love',
 'text',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'min',
 'make',
 'night',
 'dear',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'oh',
 'hope',
 'claim',
 'great',
 'hey',
 'give',
 'number',
 'happy',
 'wat',
 'friend',
 'work',
 'way',
 'yes',
 'www',
 'prize',
 'let',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'win',
 'said',
 'life',
 'cash',
 'amp',
 'yeah',
 'im',
 'really',
 'meet',
 'babe',
 'find',
 'miss',
 'morning',
 'thanks',
 'last',
 'uk',
 'service',
 'year',
 'anything',
 'care',
 'would',
 'com',
 'also',
 'lol',
 'nokia',
 'feel',
 'every',
 'keep',
 'sure',
 'pick',
 'urgent',
 'sent',
 'contact',


In [84]:
model.corpus_count

5564

In [85]:
model.epochs

5

In [86]:
model.wv.similar_by_word('love')

[('day', 0.9997552037239075),
 ('life', 0.9997438192367554),
 ('hope', 0.9997332692146301),
 ('much', 0.9997141361236572),
 ('say', 0.9997125864028931),
 ('one', 0.999701201915741),
 ('amp', 0.9996934533119202),
 ('thing', 0.9996920824050903),
 ('need', 0.999688446521759),
 ('keep', 0.9996857047080994)]

In [117]:
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if wd in model.wv.index_to_key], axis=0)

In [91]:
!pip install tqdm

In [92]:
words[73]

['performed']

In [99]:
from tqdm import tqdm

In [107]:
#apply for the entire sentences
X =[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|          | 0/5564 [00:00<?, ?it/s]c:\Users\Abhilash\anaconda3\envs\nlp\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning:

Mean of empty slice.

c:\Users\Abhilash\anaconda3\envs\nlp\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning:

invalid value encountered in scalar divide

100%|██████████| 5564/5564 [00:00<00:00, 6501.99it/s]


In [108]:
type(X)

list

In [115]:
X[0].shape

(100,)

In [116]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [123]:
X_new = np.array(X, dtype='object')

In [124]:
X_new

array([array([-0.10658413,  0.29494914,  0.14819552,  0.02014074,  0.03599965,
              -0.32475463,  0.09074865,  0.5137086 , -0.16747622, -0.15223978,
              -0.15570608, -0.34229544, -0.00505284,  0.09250941,  0.08043007,
              -0.27897057,  0.02163538, -0.3342668 , -0.01612483, -0.44722676,
               0.07198446,  0.14845988,  0.09894961, -0.1267247 , -0.10701776,
               0.02881711, -0.20891498, -0.14058192, -0.22054888,  0.05116433,
               0.29741123,  0.05887024,  0.15224785, -0.23344378, -0.12053654,
               0.26379374,  0.03137783, -0.19957583, -0.17500602, -0.37934068,
               0.06050913, -0.23403211, -0.08823698,  0.04424762,  0.24621694,
              -0.13314067, -0.18283911,  0.02927099,  0.13981406,  0.24049915,
               0.17010319, -0.27772483, -0.05984928, -0.01997829, -0.1292017 ,
               0.20463352,  0.1717142 , -0.03717199, -0.27152076,  0.0595705 ,
               0.1035594 ,  0.11647134, -0.12385344,

In [125]:
X_new[5]

array([-1.18607879e-01,  3.29238385e-01,  1.69318587e-01,  3.00193243e-02,
        4.39010039e-02, -3.63463581e-01,  9.80826542e-02,  5.77902436e-01,
       -1.92403048e-01, -1.70474693e-01, -1.77276134e-01, -3.82434338e-01,
       -5.40510239e-03,  1.11642487e-01,  9.01559144e-02, -3.14454377e-01,
        2.48224828e-02, -3.73810321e-01, -1.75472070e-02, -5.04223049e-01,
        8.28156918e-02,  1.63617089e-01,  1.14032529e-01, -1.48058027e-01,
       -1.19387649e-01,  3.65499668e-02, -2.33459651e-01, -1.56178042e-01,
       -2.45113522e-01,  5.79517521e-02,  3.41299862e-01,  6.70711473e-02,
        1.75444633e-01, -2.59851247e-01, -1.28739432e-01,  2.95722365e-01,
        3.57337035e-02, -2.26762474e-01, -1.97821215e-01, -4.32480633e-01,
        6.29056320e-02, -2.64630139e-01, -9.28279087e-02,  5.05178310e-02,
        2.77229697e-01, -1.49148315e-01, -2.04475567e-01,  3.16562988e-02,
        1.58798307e-01,  2.69638002e-01,  1.92560479e-01, -3.11032116e-01,
       -7.40920156e-02, -

In [127]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

ValueError: Found input variables with inconsistent numbers of samples: [5564, 5572]

In [128]:
X_new.shape

(5564,)

In [130]:
y.shape

(5572,)